name: moto_dash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # To keep screen awake & contorl brightness
  screen_brightness: ^2.1.7
  wakelock_plus: ^1.4.0
  # For media control
  flutter_media_controller: ^1.0.0
  # For volume control
  volume_controller: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
